import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import Courses from '../components/Courses'
import {AuthContext, useAuth} from '../context/AuthContext'
import AccessDenied from "../components/AccessDenied";
import {useContext} from "react";

export default function Home() {
  //const {currentUser, isAdmin} = useAuth()
    const {currentUser, isAdmin} =  useContext(AuthContext)

  return (
      < >
        <Head>
          <title>Course List</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        {!currentUser && <Login/>}
        {currentUser && isAdmin && <Courses/>}
        {currentUser && !isAdmin && <AccessDenied/>}
      </>
  )
}
