import Head from 'next/head';
import { useAuth } from '../context/AuthContext';
import Login from '../components/Login';
import Homepage from '../components/Homepage';
import AccessDenied from '../components/AccessDenied';
import Layout from '../components/Layout';

export default function Home() {
    const { currentUser, isAdmin } = useAuth();
//      <Layout>      </Layout>
    return (
        <>
            <Head>
                <title>Italian App Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!currentUser && <Login />}
            {currentUser && isAdmin && (

                    <Homepage />

            )}
            {currentUser && !isAdmin && <AccessDenied />}
        </>
    );
}
