import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import Users from '../components/Users'
import {AuthContext} from '../context/AuthContext'
import AccessDenied from "../components/AccessDenied";
import {useContext} from "react";


export default function Home() {

  const {currentUser, isAdmin} =  useContext(AuthContext)

  return (
      < >
        <Head>
          <title>Users List</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        {!currentUser && <AccessDenied/>}
        {currentUser && isAdmin && <Users/>}
        {currentUser && !isAdmin && <AccessDenied/>}
      </>
  )
}
